// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu92S_gpXrtOT0FB0w3gq3KSg0EQ3Eh3A',
    appId: '1:273449158441:web:e2f213de6fbd4e5038d938',
    messagingSenderId: '273449158441',
    projectId: 'chat-app-a9ef4',
    authDomain: 'chat-app-a9ef4.firebaseapp.com',
    storageBucket: 'chat-app-a9ef4.appspot.com',
    measurementId: 'G-K2SD1SR0WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BRy_BMEeYfDGsxgr9eyPdpiKG7gZP-A',
    appId: '1:273449158441:android:5de0884456ab85f738d938',
    messagingSenderId: '273449158441',
    projectId: 'chat-app-a9ef4',
    storageBucket: 'chat-app-a9ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7SMTqxLkvrqp9mpvp69lfg-aZt5DBNq0',
    appId: '1:273449158441:ios:610d7aeef19376c638d938',
    messagingSenderId: '273449158441',
    projectId: 'chat-app-a9ef4',
    storageBucket: 'chat-app-a9ef4.appspot.com',
    iosBundleId: 'com.example.chattyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7SMTqxLkvrqp9mpvp69lfg-aZt5DBNq0',
    appId: '1:273449158441:ios:53002abe52248aac38d938',
    messagingSenderId: '273449158441',
    projectId: 'chat-app-a9ef4',
    storageBucket: 'chat-app-a9ef4.appspot.com',
    iosBundleId: 'com.example.chattyApp.RunnerTests',
  );
}
